# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SimpleWeatherApp' do

pod "AFNetworking", '~> 2.0'
pod "AFNetworkingLogger", :git => 'https://github.com/stanislaw/AFNetworkingLogger'
pod "CRToast"

end

target 'SimpleWeatherAppTests' do

end

